baseURL = "https://www.brucebrotherton.com/"
disableLanguages = []
disqusShortname = "brucebrotherton"
googleAnalytics = "G-32H9G3NJDD"
languageCode = "en-us"
languageName = "En"
paginate = "6"
summaryLength = "10"
theme = "bbrother"
title = "Bruce Brotherton's Blog"
[markup.goldmark.renderer]
unsafe = true
[[menu.desktop]]
URL = "contact"
name = "Contact"
weight = 4
[[menu.desktop]]
URL = "https://www.teepublic.com/user/thebruce13"
name = "T-Shirts"
weight = 3
[[menu.desktop]]
URL = "blog"
name = "Blog"
weight = 1
[[menu.main]]
URL = "/"
name = "Home"
weight = 1
[[menu.main]]
URL = "about"
name = "About"
weight = 4
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 5
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 6
[[menu.main]]
name = "T-shirts"
url = "https://www.teepublic.com/user/thebruce13"
weight = 3
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Bruce Brotherton"
description = "A blog about Web Development, 3D Graphics, Trying to write a novel, and maybe making a video game. Its anything and everyhing I am into."
[params.banner]
heading = "Bruce's Backpack"
image = "/images/webpack-render-s.png"
[params.blog]
heading = "Posts from within my backpack. A random collection of thoughts and ideas."
[params.call_to_action]
button_label = "Contact Us"
button_url = "contact"
content = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis"
enable = false
title = "Contact us for more information."
[params.footer]
address = ""
content = "A blog about Web Development, 3D Graphics, Trying to write a novel, and maybe making a video game. Its anything and everything I am into. Welcome."
copyright = "Copyright &copy; 2022"
hours = ""
title = "About This Site"
[params.gallery]
enable = true
[[params.gallery.gallery_item]]
image = "/images/suzan-slime-10.webp"
[[params.gallery.gallery_item]]
image = "/images/selfie-collection.jpg"
[params.social]
email = "brucemfbrotherton@gmail.com"
facebook = ""
instagram = "https://www.instagram.com/bruce.brotherton/"
linkedin = "https://www.linkedin.com/in/brothertonbruce/"
twitter = "https://twitter.com/brucebrotherton"
yelp = ""
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
