baseURL = "https://www.brucebrotherton.com/"
disableLanguages = []
disqusShortname = "brucebrotherton"
googleAnalytics = "G-32H9G3NJDD"
languageCode = "en-us"
languageName = "En"
paginate = "6"
summaryLength = "10"
theme = "bbrother"
title = "Bruce's Brackets"
[markup.goldmark.renderer]
unsafe = true
[[menu.desktop]]
URL = "contact"
name = "Contact"
weight = 4
[[menu.desktop]]
URL = "https://www.teepublic.com/user/thebruce13"
name = "T-Shirts"
weight = 3
[[menu.desktop]]
URL = "blog"
name = "Blog"
weight = 1
[[menu.main]]
URL = "/"
name = "Home"
weight = 1
[[menu.main]]
URL = "about"
name = "About"
weight = 4
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 5
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 6
[[menu.main]]
name = "T-shirts"
url = "https://www.teepublic.com/user/thebruce13"
weight = 3
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Bruce Brotherton"
description = "A blog about Web Development, 3D Graphics, Trying to write a novel, and maybe making a video game. Its anything and everyhing I am into."
[params.banner]
heading = "Bruce's Brackets"
description="<p>Hi, I'm Bruce Brotherton and welcome to my blog. I am working on making content that helps developers understand CSS using practical examples and diving into the nitty-gritty of properties so we can all understand what is really going on when we set up values.</p><p>Along the way I’ll be talking about my personal interactions with tech and hopefully giving some guidance with my struggles and triumphs.</p><p>I am also a tinkerer with computer graphics so I hope to share my creations with that. Weather they are my images for my posts or new t-shirt designs that are up for sale.</p><p>That’s all for now, come along if you want to.</p>"
image = "/images/webpack-render-s.png"
[params.blog]
heading = "Posts that dive into CSS, Websites, and Technology"
[params.call_to_action]
button_label = "Show your support by buying me one. ☕"
button_url = "https://www.paypal.com/paypalme/brucebrotherton"
title = "Like what I’m doing here?"
content = "<p>I'm working hard to create content that is informative and engaging for you - and I wouldn't say no to a (virtual) cup of coffee!</p>"
enable = true
[params.footer]
address = ""
content = "A blog about Web Development, 3D Graphics, Trying to write a novel, and maybe making a video game. Its anything and everything I am into. Welcome."
copyright = "Copyright &copy; 2022"
hours = ""
title = "About This Site"
[params.gallery]
enable = true
[[params.gallery.gallery_item]]
image = "/images/suzan-slime-10.webp"
[[params.gallery.gallery_item]]
image = "/images/selfie-collection.jpg"
[params.social]
email = "brucemfbrotherton@gmail.com"
facebook = ""
instagram = "https://www.instagram.com/bruce.brotherton/"
linkedin = "https://www.linkedin.com/in/brothertonbruce/"
twitter = "https://twitter.com/brucebrotherton"
yelp = ""
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
