[build]
  publish = "public"
  command = "hugo"
  
[build.environment]
  HUGO_VERSION = "0.69.0"

[[redirects]]
  from = "/rss"
  to = "/blog/index.xml"
  status = 301
  force = true # COMMENT: ensure that we always redirect
