[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --gc --themesDir ../.."
  
[build.environment]
  HUGO_VERSION = "0.69.0"
  HUGO_THEME = "repo"

[[redirects]]
  from = "/rss"
  to = "/blog/index.xml"
  status = 301
  force = true # COMMENT: ensure that we always redirect
