[build]
  publish = "public"
<<<<<<< HEAD
  command = "hugo --gc --themesDir ../.."
=======
  command = "hugo"
>>>>>>> d491330cf8345077021b0ab496a38299477d0cc9
  
[build.environment]
  HUGO_VERSION = "0.69.0"

[[redirects]]
  from = "/rss"
  to = "/blog/index.xml"
  status = 301
  force = true # COMMENT: ensure that we always redirect
